### ISSUE TITLE
[BUG] Unable to find version '17'

### ISSUE THREAD

**Issue by cyschneck** [tj-actions/verify-changed-files#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I believe I am using the most recent version `tj-actions/verify-changed-files@17`. This command ran as expected this time last month, but this time it failing from:
```
build
Unable to resolve action `tj-actions/verify-changed-files@17`, unable to find version `17`
```
The most recent version is 17.1.0, does it no longer accept 17 as a version number like in the documentation?

### To Reproduce

1. Ubuntu-20.04 github action
2. [Script, line 42](https://github.com/unaschneck/pydar/actions/runs/7734676876/workflow)
```
Unable to resolve action `tj-actions/verify-changed-files@17`, unable to find version `17`
```

### What OS are you seeing the problem on?

ubuntu-20.04

### Expected behavior?

Github Actions does not recognize version 17, but ran as expected a month ago. Is the syntax different than the documentation to work with the newest release?

### Relevant log output

```shell
##[debug]Starting: Set up job
Current runner version: '2.312.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
##[debug]Primary repository: unaschneck/pydar
Prepare workflow directory
##[debug]Creating pipeline directory: '/home/runner/work/pydar'
##[debug]Creating workspace directory: '/home/runner/work/pydar/pydar'
##[debug]Update context data
##[debug]Evaluating job-level environment variables
##[debug]Evaluating job container
##[debug]Evaluating job service containers
##[debug]Evaluating job defaults
Prepare all required actions
Getting action download info
Error: Unable to resolve action `tj-actions/verify-changed-files@17`, unable to find version `17`
##[debug]GitHub.DistributedTask.WebApi.UnresolvableActionDownloadInfoException: Unable to resolve action `tj-actions/verify-changed-files@17`, unable to find version `17`
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
##[debug]   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

[Script generating the error](https://github.com/unaschneck/pydar/actions/runs/7734676876/workflow), but script is not able to run since Github Actions does not recognize version 17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
HI @cyschneck, I believe you are missing a `v` it should be `tj-actions/verify-changed-files@v17` instead of `tj-actions/verify-changed-files@17`
